FROM ubuntu:18.04

COPY sources_bionic.list /etc/apt/sources.list
COPY entry_point.sh /entry_point.sh
COPY rknn_toolkit2-1.5.0+1fa95b5c-cp36-cp36m-linux_x86_64.whl rknn_toolkit2-1.5.0+1fa95b5c-cp36-cp36m-linux_x86_64.whl

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
	&& apt-get install -y python3 python3-dev python3-pip gcc vim libprotobuf-dev zlib1g zlib1g-dev libsm6 \
	&& apt-get install -y libgl1 libglib2.0-0 android-tools-adb openssh-client openssh-server

RUN cd /usr/bin \
	&& ln -sfn idle3 idle \
	&& ln -sfn pydoc3 pydoc \
	&& ln -sfn python3 python \
	&& ln -sfn python3-config python-config \
	&& ln -sfn pip3 pip \
	&& ls -al

RUN python -m pip install --upgrade pip -i https://mirror.baidu.com/pypi/simple --trusted-host=mirror.baidu.com \
	&& pip3 config set global.index-url https://mirror.baidu.com/pypi/simple \
	&& pip3 config set install.trusted-host mirror.baidu.com

RUN python3 --version \
	&& pip3 --version \
	&& pip3 install rknn_toolkit2-1.5.0+1fa95b5c-cp36-cp36m-linux_x86_64.whl

RUN mkdir /run/sshd \
	&& sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config \
	&& echo "root:123456" | chpasswd \
	&& chmod +x /entry_point.sh
